<?xml version="1.0" encoding="utf-8"?>
<feature>
	<version>1</version>
	<uuid/>
	<name>Global Min/Max: Temperature (Solid)</name>
	<type>13</type>
	<res_file_key>58c1d0f6-90bf-4398-b072-2bfe19aba9d5</res_file_key>
	<cs_name/>
	<cs_uuid/>
	<x_form>
		<global>true</global>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<translate>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
		</translate>
	</x_form>
	<display_bl>false</display_bl>
	<interpolate>true</interpolate>
	<use_cad_geom>false</use_cad_geom>
	<moving_reference>true</moving_reference>
	<moving_display>true</moving_display>
	<full_task>false</full_task>
	<use_in_BRP>false</use_in_BRP>
	<parameter>
		<uuid>FCD5C2E4-1ECA-47a3-BC2C-E56DF50A118B</uuid>
		<name>Temperature (Solid)</name>
		<unit>20</unit>
		<formula/>
		<formula2/>
		<formula3/>
		<locality>0</locality>
	</parameter>
</feature>
