<?xml version="1.0" encoding="utf-8"?>
<feature>
	<version>1</version>
	<uuid>c20a29cf-bd78-4d13-a70c-088b7985ff53</uuid>
	<name>Points</name>
	<type>19</type>
	<res_file_key>c54b3987-ec34-4431-8db3-ff47cba9ee7f</res_file_key>
	<cs_name/>
	<cs_uuid/>
	<x_form>
		<global>true</global>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<translate>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
		</translate>
	</x_form>
	<display_bl>false</display_bl>
	<interpolate>true</interpolate>
	<use_cad_geom>true</use_cad_geom>
	<moving_reference>true</moving_reference>
	<moving_display>true</moving_display>
	<full_task>false</full_task>
	<use_in_BRP>false</use_in_BRP>
	<use_all_faces>false</use_all_faces>
	<geom_ref>
		<item>
			<uuid>1811f6a6-3f8c-4e1c-9661-2e241cc907c3</uuid>
			<name>Face&lt;1&gt;@Condensador_Espiral&lt;1&gt;</name>
			<type>1</type>
			<id1>0</id1>
			<id2>0</id2>
			<update_stamp>0</update_stamp>
			<group>-1</group>
			<geom_stamp_uuid>6b6fd170-c450-4291-9204-1cf38661ca59</geom_stamp_uuid>
			<origin>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</origin>
			<normal>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</normal>
			<vector>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</vector>
			<pos>0</pos>
			<flip>1</flip>
			<min>0</min>
			<max>0</max>
			<curve_data>
				<start>0</start>
				<end>0</end>
				<length>0</length>
				<data/>
			</curve_data>
			<path>
				<path_elems/>
			</path>
		</item>
		<item>
			<uuid>83378234-eddb-4b2d-9116-158d016b3a4e</uuid>
			<name>Face&lt;2&gt;@Condensador_Espiral&lt;1&gt;</name>
			<type>1</type>
			<id1>0</id1>
			<id2>0</id2>
			<update_stamp>0</update_stamp>
			<group>-1</group>
			<geom_stamp_uuid>6b6fd170-c450-4291-9204-1cf38661ca59</geom_stamp_uuid>
			<origin>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</origin>
			<normal>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</normal>
			<vector>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</vector>
			<pos>0</pos>
			<flip>1</flip>
			<min>0</min>
			<max>0</max>
			<curve_data>
				<start>0</start>
				<end>0</end>
				<length>0</length>
				<data/>
			</curve_data>
			<path>
				<path_elems/>
			</path>
		</item>
		<item>
			<uuid>f6ad1709-76eb-41cd-8316-5d4c0987f70e</uuid>
			<name>Face&lt;3&gt;@Condensador_Espiral&lt;1&gt;</name>
			<type>1</type>
			<id1>0</id1>
			<id2>0</id2>
			<update_stamp>0</update_stamp>
			<group>-1</group>
			<geom_stamp_uuid>6b6fd170-c450-4291-9204-1cf38661ca59</geom_stamp_uuid>
			<origin>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</origin>
			<normal>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</normal>
			<vector>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</vector>
			<pos>0</pos>
			<flip>1</flip>
			<min>0</min>
			<max>0</max>
			<curve_data>
				<start>0</start>
				<end>0</end>
				<length>0</length>
				<data/>
			</curve_data>
			<path>
				<path_elems/>
			</path>
		</item>
	</geom_ref>
	<point/>
	<points_def_mode>0</points_def_mode>
	<purpose>0</purpose>
	<points_table_def_mode>0</points_table_def_mode>
	<points_analytic_def_mode>0</points_analytic_def_mode>
	<points_analytic_def_line>
		<p1>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</p1>
		<p2>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</p2>
	</points_analytic_def_line>
	<points_analytic_def_rect>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<normal>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</normal>
		<up>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</up>
		<width>0</width>
		<height>0</height>
	</points_analytic_def_rect>
	<points_analytic_def_sphere>
		<center>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</center>
		<radius>0</radius>
	</points_analytic_def_sphere>
	<points_count>20</points_count>
	<points_spacing>0.0040000000000000001</points_spacing>
	<use_mesh_based_point_generation>false</use_mesh_based_point_generation>
	<file_path/>
	<file_time>0</file_time>
	<media>false</media>
</feature>
