<?xml version="1.0" encoding="utf-8"?>
<feature>
	<version>1</version>
	<uuid>2cd8aec7-9e8a-450c-a127-5575c7274251</uuid>
	<name>Points</name>
	<type>19</type>
	<res_file_key>a5b82267-e945-4b0b-b878-79e861b564a3</res_file_key>
	<cs_name/>
	<cs_uuid/>
	<x_form>
		<global>true</global>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<translate>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
		</translate>
	</x_form>
	<display_bl>false</display_bl>
	<interpolate>true</interpolate>
	<use_cad_geom>true</use_cad_geom>
	<moving_reference>true</moving_reference>
	<moving_display>true</moving_display>
	<full_task>false</full_task>
	<use_in_BRP>false</use_in_BRP>
	<use_all_faces>false</use_all_faces>
	<geom_ref>
		<item>
			<uuid>f6ad1709-76eb-41cd-8316-5d4c0987f70e</uuid>
			<name>Face&lt;4&gt;@Condensador_Espiral&lt;1&gt;</name>
			<type>1</type>
			<id1>0</id1>
			<id2>0</id2>
			<update_stamp>0</update_stamp>
			<group>-1</group>
			<geom_stamp_uuid>f70f53df-aaa5-4b1e-a845-7db0f066e920</geom_stamp_uuid>
			<origin>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</origin>
			<normal>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</normal>
			<vector>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</vector>
			<pos>0</pos>
			<flip>1</flip>
			<min>0</min>
			<max>0</max>
			<curve_data>
				<start>0</start>
				<end>0</end>
				<length>0</length>
				<data/>
			</curve_data>
			<path>
				<path_elems/>
			</path>
		</item>
		<item>
			<uuid>bddb6460-0d58-4c89-af10-72e2aabd8c83</uuid>
			<name>Face&lt;5&gt;@Condensador_Espiral&lt;1&gt;</name>
			<type>1</type>
			<id1>0</id1>
			<id2>0</id2>
			<update_stamp>0</update_stamp>
			<group>-1</group>
			<geom_stamp_uuid>f70f53df-aaa5-4b1e-a845-7db0f066e920</geom_stamp_uuid>
			<origin>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</origin>
			<normal>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</normal>
			<vector>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</vector>
			<pos>0</pos>
			<flip>1</flip>
			<min>0</min>
			<max>0</max>
			<curve_data>
				<start>0</start>
				<end>0</end>
				<length>0</length>
				<data/>
			</curve_data>
			<path>
				<path_elems/>
			</path>
		</item>
		<item>
			<uuid>f8bd55f5-a076-49ab-8825-ebd648c3a638</uuid>
			<name>Face&lt;6&gt;@Condensador_Espiral&lt;1&gt;</name>
			<type>1</type>
			<id1>0</id1>
			<id2>0</id2>
			<update_stamp>0</update_stamp>
			<group>-1</group>
			<geom_stamp_uuid>f70f53df-aaa5-4b1e-a845-7db0f066e920</geom_stamp_uuid>
			<origin>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</origin>
			<normal>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</normal>
			<vector>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</vector>
			<pos>0</pos>
			<flip>1</flip>
			<min>0</min>
			<max>0</max>
			<curve_data>
				<start>0</start>
				<end>0</end>
				<length>0</length>
				<data/>
			</curve_data>
			<path>
				<path_elems/>
			</path>
		</item>
	</geom_ref>
	<point/>
	<points_def_mode>0</points_def_mode>
	<purpose>0</purpose>
	<points_table_def_mode>0</points_table_def_mode>
	<points_analytic_def_mode>0</points_analytic_def_mode>
	<points_analytic_def_line>
		<p1>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</p1>
		<p2>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</p2>
	</points_analytic_def_line>
	<points_analytic_def_rect>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<normal>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</normal>
		<up>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</up>
		<width>0</width>
		<height>0</height>
	</points_analytic_def_rect>
	<points_analytic_def_sphere>
		<center>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</center>
		<radius>0</radius>
	</points_analytic_def_sphere>
	<points_count>20</points_count>
	<points_spacing>0.002</points_spacing>
	<use_mesh_based_point_generation>false</use_mesh_based_point_generation>
	<file_path/>
	<file_time>0</file_time>
	<media>false</media>
</feature>
