<?xml version="1.0" encoding="utf-8"?>
<feature>
	<version>1</version>
	<uuid>cee3879f-69fa-4203-b17a-292355150514</uuid>
	<name>Flow Trajectories 1</name>
	<type>8</type>
	<res_file_key>34ab6133-22d2-4e6a-9561-c6c8bddde046</res_file_key>
	<cs_name/>
	<cs_uuid/>
	<x_form>
		<global>true</global>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<translate>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
		</translate>
	</x_form>
	<display_bl>false</display_bl>
	<interpolate>true</interpolate>
	<use_cad_geom>true</use_cad_geom>
	<moving_reference>true</moving_reference>
	<moving_display>true</moving_display>
	<full_task>false</full_task>
	<use_in_BRP>false</use_in_BRP>
	<transparency>0</transparency>
	<box>
		<item>0.62968319727689548</item>
		<item>0.78843692261998233</item>
		<item>0.85841511112524116</item>
		<item>1.0628398190175976</item>
		<item>1.2682042511548328</item>
		<item>1.4144571574544915</item>
	</box>
	<crop_region_anchors>
		<item>false</item>
		<item>false</item>
		<item>false</item>
		<item>false</item>
		<item>false</item>
		<item>false</item>
	</crop_region_anchors>
	<section_plane/>
	<use_all_faces>false</use_all_faces>
	<geom_ref>
		<item>
			<uuid>60b1c05a-4c23-4cf8-8adc-6bbff11c16c9</uuid>
			<name>Face&lt;1&gt;@Base_Torre&lt;1&gt;</name>
			<type>1</type>
			<id1>0</id1>
			<id2>0</id2>
			<update_stamp>0</update_stamp>
			<group>-1</group>
			<geom_stamp_uuid>4d6d570e-fe48-4c98-903b-f13b6be8ccc7</geom_stamp_uuid>
			<origin>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</origin>
			<normal>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</normal>
			<vector>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</vector>
			<pos>0</pos>
			<flip>1</flip>
			<min>0</min>
			<max>0</max>
			<curve_data>
				<start>0</start>
				<end>0</end>
				<length>0</length>
				<data/>
			</curve_data>
			<path>
				<path_elems/>
			</path>
		</item>
	</geom_ref>
	<point/>
	<points_def_mode>0</points_def_mode>
	<purpose>0</purpose>
	<points_table_def_mode>0</points_table_def_mode>
	<points_analytic_def_mode>0</points_analytic_def_mode>
	<points_analytic_def_line>
		<p1>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</p1>
		<p2>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</p2>
	</points_analytic_def_line>
	<points_analytic_def_rect>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<normal>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</normal>
		<up>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</up>
		<width>0</width>
		<height>0</height>
	</points_analytic_def_rect>
	<points_analytic_def_sphere>
		<center>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</center>
		<radius>0</radius>
	</points_analytic_def_sphere>
	<points_count>20</points_count>
	<points_spacing>0.0050000000000000001</points_spacing>
	<use_mesh_based_point_generation>false</use_mesh_based_point_generation>
	<file_path/>
	<file_time>0</file_time>
	<abscissa/>
	<palette>
		<uuid>d63ff3e3-a56b-476c-87c2-66371d2f2650</uuid>
		<parameter>
			<uuid>10D4FAE8-644D-4066-B057-01CB07D22173</uuid>
			<name/>
			<unit>0</unit>
			<formula/>
			<formula2/>
			<formula3/>
			<locality>0</locality>
		</parameter>
		<param_min>
			<value>293.1999995105752</value>
			<is_initialized>true</is_initialized>
			<is_global>true</is_global>
			<is_plot>false</is_plot>
		</param_min>
		<param_max>
			<value>366.64999999999998</value>
			<is_initialized>true</is_initialized>
			<is_global>true</is_global>
			<is_plot>false</is_plot>
		</param_max>
		<cs_uuid/>
		<cs_xform>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</cs_xform>
		<color_palette>5</color_palette>
		<ncolors>9</ncolors>
		<outer_minmax_coloring>0</outer_minmax_coloring>
		<outer_min_color>16711680</outer_min_color>
		<outer_max_color>255</outer_max_color>
		<outer_colors_display>true</outer_colors_display>
		<logarithmic>false</logarithmic>
		<custom_params_maxs>
			<88A4B00C-3C32-4822-94C2-4682145D4F95>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</88A4B00C-3C32-4822-94C2-4682145D4F95>
		</custom_params_maxs>
		<custom_params_mins>
			<88A4B00C-3C32-4822-94C2-4682145D4F95>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</88A4B00C-3C32-4822-94C2-4682145D4F95>
		</custom_params_mins>
		<cs_name>Global Coordinate System</cs_name>
		<display_plot_names>true</display_plot_names>
		<display_plot_minmaxes>false</display_plot_minmaxes>
		<display_title>false</display_title>
		<title/>
		<auto_scale_font>false</auto_scale_font>
		<use_default_font>true</use_default_font>
		<font>
			<name/>
			<size>9</size>
			<color>0</color>
			<font_isbold>false</font_isbold>
			<font_isitalic>false</font_isitalic>
		</font>
		<bkgd_color>16777215</bkgd_color>
		<bkgd_transp>1</bkgd_transp>
		<x>0</x>
		<y>0</y>
		<width>20</width>
		<height>200</height>
		<auto_ticks>true</auto_ticks>
		<ticks_number>11</ticks_number>
		<vertical>3</vertical>
		<rot_text>false</rot_text>
		<is_user_pos>false</is_user_pos>
	</palette>
	<color_by_param>true</color_by_param>
	<color>16711680</color>
	<style>3</style>
	<line_width>2</line_width>
	<cross_size>0.001</cross_size>
	<traj_type>0</traj_type>
	<dyn_traj_style>0</dyn_traj_style>
	<dyn_traj_width>10</dyn_traj_width>
	<dyn_traj_spacing>25</dyn_traj_spacing>
	<max_length>2</max_length>
	<max_time>3600</max_time>
	<max_t_step>50000</max_t_step>
	<relative_to_abs_frame>true</relative_to_abs_frame>
	<flow_trajectories_type>0</flow_trajectories_type>
	<direction>0</direction>
	<particle_uuid>
		<item>
			<uuid>80BB91D8-944B-484e-8643-7D8836B75717</uuid>
			<name/>
			<unit>0</unit>
			<formula/>
			<formula2/>
			<formula3/>
			<locality>0</locality>
		</item>
		<item>
			<uuid>5C3A4D89-ABB1-4605-8230-05F66BE5E4BA</uuid>
			<name/>
			<unit>0</unit>
			<formula/>
			<formula2/>
			<formula3/>
			<locality>0</locality>
		</item>
		<item>
			<uuid>7C8CD2FB-54C6-4d82-8100-303AE1009345</uuid>
			<name/>
			<unit>0</unit>
			<formula/>
			<formula2/>
			<formula3/>
			<locality>0</locality>
		</item>
		<item>
			<uuid>56EDA0C2-098F-4d15-A028-EFE02E12C801</uuid>
			<name/>
			<unit>0</unit>
			<formula/>
			<formula2/>
			<formula3/>
			<locality>0</locality>
		</item>
		<item>
			<uuid>FCF692CF-885D-433f-8F40-0E2629F0B3EC</uuid>
			<name/>
			<unit>0</unit>
			<formula/>
			<formula2/>
			<formula3/>
			<locality>0</locality>
		</item>
	</particle_uuid>
	<fluid_res_uuid/>
	<particle_res_uuid/>
	<save_to_ASCII>false</save_to_ASCII>
	<ASCII_file/>
</feature>
