<?xml version="1.0" encoding="utf-8"?>
<feature>
	<version>1</version>
	<uuid>2761d1a6-f6a3-48dd-a884-c809e19bed3b</uuid>
	<name>Cut Plot 1</name>
	<type>0</type>
	<res_file_key>d46efdd6-29b0-413b-b9ca-0fc2f9309904</res_file_key>
	<cs_name/>
	<cs_uuid/>
	<x_form>
		<global>true</global>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<translate>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
		</translate>
	</x_form>
	<display_bl>false</display_bl>
	<interpolate>true</interpolate>
	<use_cad_geom>true</use_cad_geom>
	<moving_reference>false</moving_reference>
	<moving_display>false</moving_display>
	<full_task>false</full_task>
	<use_in_BRP>false</use_in_BRP>
	<transparency>0</transparency>
	<box>
		<item>-0.122128008</item>
		<item>0.002128007999999995</item>
		<item>-5.5000000000015953e-05</item>
		<item>0.055055000000000021</item>
		<item>-0.050054004000000013</item>
		<item>5.0004000000020855e-05</item>
	</box>
	<crop_region_anchors>
		<item>false</item>
		<item>false</item>
		<item>false</item>
		<item>false</item>
		<item>false</item>
		<item>false</item>
	</crop_region_anchors>
	<section_plane/>
	<use_all_faces>false</use_all_faces>
	<geom_ref>
		<item>
			<uuid>62e21a87-7a09-4b8a-91be-e650b0515b6a</uuid>
			<name>Front Plane</name>
			<type>0</type>
			<id1>0</id1>
			<id2>0</id2>
			<update_stamp>101</update_stamp>
			<group>-1</group>
			<geom_stamp_uuid>f70f53df-aaa5-4b1e-a845-7db0f066e920</geom_stamp_uuid>
			<origin>
				<item>-0.060000000000000005</item>
				<item>0.027500000000000004</item>
				<item>0</item>
			</origin>
			<normal>
				<item>0</item>
				<item>0</item>
				<item>1</item>
			</normal>
			<vector>
				<item>1</item>
				<item>0</item>
				<item>0</item>
			</vector>
			<pos>-0.024890669599999998</pos>
			<flip>1</flip>
			<min>-0.050054004000000013</min>
			<max>5.0004000000020855e-05</max>
			<curve_data>
				<start>0</start>
				<end>0</end>
				<length>0</length>
				<data/>
			</curve_data>
			<path>
				<path_elems/>
			</path>
		</item>
	</geom_ref>
	<domain_filter>
		<enabled>false</enabled>
		<keep>true</keep>
		<type>0</type>
		<domains/>
	</domain_filter>
	<contours>
		<display>true</display>
		<palette>
			<uuid>ff1752a2-d4a8-453e-9b6c-5d5b09209e9c</uuid>
			<parameter>
				<uuid>10D4FAE8-644D-4066-B057-01CB07D22173</uuid>
				<name>Temperature (Fluid)</name>
				<unit>20</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>293.19999999999999</value>
				<is_initialized>true</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>600</value>
				<is_initialized>true</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>9</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>true</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs>
				<88A4B00C-3C32-4822-94C2-4682145D4F95>
					<value>0</value>
					<is_initialized>false</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</88A4B00C-3C32-4822-94C2-4682145D4F95>
				<10D4FAE8-644D-4066-B057-01CB07D22173>
					<value>600</value>
					<is_initialized>true</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</10D4FAE8-644D-4066-B057-01CB07D22173>
			</custom_params_maxs>
			<custom_params_mins>
				<88A4B00C-3C32-4822-94C2-4682145D4F95>
					<value>0</value>
					<is_initialized>false</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</88A4B00C-3C32-4822-94C2-4682145D4F95>
				<10D4FAE8-644D-4066-B057-01CB07D22173>
					<value>293.11228771218578</value>
					<is_initialized>true</is_initialized>
					<is_global>true</is_global>
					<is_plot>false</is_plot>
				</10D4FAE8-644D-4066-B057-01CB07D22173>
			</custom_params_mins>
			<cs_name>Global Coordinate System</cs_name>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name>Arial</name>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>339</x>
			<y>38</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>true</is_user_pos>
		</palette>
		<color_by_param>true</color_by_param>
		<color>16711680</color>
	</contours>
	<min_callout>
		<display>false</display>
		<coordinates>false</coordinates>
		<appearance>
			<title>true</title>
			<title_source>0</title_source>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<value_color>16777215</value_color>
			<title_color>16758122</title_color>
			<line_color>0</line_color>
			<auto_line_color>true</auto_line_color>
			<transparency>0</transparency>
			<pinned>false</pinned>
			<show_results>true</show_results>
		</appearance>
		<position_initialized>false</position_initialized>
		<position>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</position>
	</min_callout>
	<max_callout>
		<display>false</display>
		<coordinates>false</coordinates>
		<appearance>
			<title>true</title>
			<title_source>0</title_source>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<value_color>16777215</value_color>
			<title_color>8026879</title_color>
			<line_color>0</line_color>
			<auto_line_color>true</auto_line_color>
			<transparency>0</transparency>
			<pinned>false</pinned>
			<show_results>true</show_results>
		</appearance>
		<position_initialized>false</position_initialized>
		<position>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</position>
	</max_callout>
	<isolines>
		<display>false</display>
		<palette>
			<uuid>51c74b9d-ca06-4395-b58c-0483a0346156</uuid>
			<parameter>
				<uuid>88A4B00C-3C32-4822-94C2-4682145D4F95</uuid>
				<name/>
				<unit>0</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>9</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>true</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs/>
			<custom_params_mins/>
			<cs_name/>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>0</x>
			<y>0</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>false</is_user_pos>
		</palette>
		<width>1</width>
		<color_by_param>true</color_by_param>
		<color>0</color>
	</isolines>
	<vectors>
		<display>false</display>
		<build_palette>
			<uuid>e05ef750-aa5d-46c9-b0ed-bfc52fed66a2</uuid>
			<parameter>
				<uuid>8A88FD9A-C36E-4151-864A-F5BC1C916074</uuid>
				<name/>
				<unit>0</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>10</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>false</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs/>
			<custom_params_mins/>
			<cs_name/>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>0</x>
			<y>0</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>false</is_user_pos>
		</build_palette>
		<palette>
			<uuid>51c74b9d-ca06-4395-b58c-0483a0346156</uuid>
			<parameter>
				<uuid>88A4B00C-3C32-4822-94C2-4682145D4F95</uuid>
				<name/>
				<unit>0</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>9</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>true</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs/>
			<custom_params_mins/>
			<cs_name/>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>0</x>
			<y>0</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>false</is_user_pos>
		</palette>
		<color_by_param>false</color_by_param>
		<color>0</color>
		<vectors_projected>true</vectors_projected>
		<arrow_size>0.002</arrow_size>
		<spacing>0.002</spacing>
		<minmax_arrowsize_ratio>0.001</minmax_arrowsize_ratio>
		<logarithmic_arrows>false</logarithmic_arrows>
		<vistype>0</vistype>
		<dynamic>
			<enabled>false</enabled>
			<width>6</width>
			<arrow_size>32</arrow_size>
			<spacing>8</spacing>
		</dynamic>
	</vectors>
	<essslic>
		<display>false</display>
		<build_palette>
			<uuid>4b0e1cfc-0eba-4b6c-a406-d7ba00dbf933</uuid>
			<parameter>
				<uuid>8A88FD9A-C36E-4151-864A-F5BC1C916074</uuid>
				<name/>
				<unit>0</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>10</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>false</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs/>
			<custom_params_mins/>
			<cs_name/>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>0</x>
			<y>0</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>false</is_user_pos>
		</build_palette>
		<palette>
			<uuid>51c74b9d-ca06-4395-b58c-0483a0346156</uuid>
			<parameter>
				<uuid>88A4B00C-3C32-4822-94C2-4682145D4F95</uuid>
				<name/>
				<unit>0</unit>
				<formula/>
				<formula2/>
				<formula3/>
				<locality>0</locality>
			</parameter>
			<param_min>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_min>
			<param_max>
				<value>0</value>
				<is_initialized>false</is_initialized>
				<is_global>true</is_global>
				<is_plot>false</is_plot>
			</param_max>
			<cs_uuid/>
			<cs_xform>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
				<item>1</item>
				<item>0</item>
				<item>0</item>
				<item>0</item>
			</cs_xform>
			<color_palette>5</color_palette>
			<ncolors>9</ncolors>
			<outer_minmax_coloring>0</outer_minmax_coloring>
			<outer_min_color>16711680</outer_min_color>
			<outer_max_color>255</outer_max_color>
			<outer_colors_display>true</outer_colors_display>
			<logarithmic>false</logarithmic>
			<custom_params_maxs/>
			<custom_params_mins/>
			<cs_name/>
			<display_plot_names>true</display_plot_names>
			<display_plot_minmaxes>false</display_plot_minmaxes>
			<display_title>false</display_title>
			<title/>
			<auto_scale_font>false</auto_scale_font>
			<use_default_font>true</use_default_font>
			<font>
				<name/>
				<size>9</size>
				<color>0</color>
				<font_isbold>false</font_isbold>
				<font_isitalic>false</font_isitalic>
			</font>
			<bkgd_color>16777215</bkgd_color>
			<bkgd_transp>1</bkgd_transp>
			<x>0</x>
			<y>0</y>
			<width>20</width>
			<height>200</height>
			<auto_ticks>true</auto_ticks>
			<ticks_number>11</ticks_number>
			<vertical>3</vertical>
			<rot_text>false</rot_text>
			<is_user_pos>false</is_user_pos>
		</palette>
		<color_by_param>false</color_by_param>
		<color>0</color>
		<vistype>0</vistype>
		<esss_vistype>0</esss_vistype>
		<esss_linespacing>12</esss_linespacing>
		<esss_linewidth>2</esss_linewidth>
		<lic_noisegrainsize>1</lic_noisegrainsize>
		<lic_noisedensity>0.5</lic_noisedensity>
		<lic_contrast>0.10000000000000001</lic_contrast>
		<lic_convsize>64</lic_convsize>
	</essslic>
	<mesh>
		<display>false</display>
		<color>0</color>
	</mesh>
	<background>
		<display>false</display>
		<color>16777215</color>
	</background>
	<outlines_display>true</outlines_display>
	<outlines_color>0</outlines_color>
	<DeformedShape>
		<uuid>672c4489-7591-4138-9da5-12f2cfd246aa</uuid>
		<creation_date>1776976408</creation_date>
		<enabled>false</enabled>
		<auto_scale>true</auto_scale>
		<scale/>
		<mode>-1</mode>
	</DeformedShape>
	<medias>
		<item>1</item>
	</medias>
	<mesh_type>0</mesh_type>
	<MeshTypePriority>0</MeshTypePriority>
	<section_def_mode>0</section_def_mode>
	<xyz_plane>0</xyz_plane>
	<points>
		<item>500</item>
		<item>500</item>
		<item>400</item>
		<item>400</item>
	</points>
	<camera>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<up>
			<item>0</item>
			<item>1</item>
			<item>0</item>
		</up>
		<direction>
			<item>0</item>
			<item>0</item>
			<item>-1</item>
		</direction>
		<scale>1</scale>
	</camera>
	<profile>
		<enabled>false</enabled>
		<grid>false</grid>
		<grid_step>0.01</grid_step>
		<bumpsize>0.002</bumpsize>
	</profile>
	<isolines_displayvalues>false</isolines_displayvalues>
	<vectors_uniformmesh>true</vectors_uniformmesh>
	<media>3</media>
</feature>
